#!/usr/bin/env python3
"""Parses mctrot_map.svg into MctrotMapData.elm and mctrot_map.css.

mctrot_map.svg is the source of truth (a real Manhattan silhouette, the 47
McDonald's locations, and a real-street routing layer where each road
segment's `class` attribute lists every location-pair whose shortest route
crosses it). This script transcodes that static SVG into:

  - src/MctrotMapData.elm: pure Elm data (no logic) that Mctrot.elm renders.
  - mctrot_map.css: base layer styles plus one CSS rule per possible
    location-pair, so Mctrot.elm only ever needs to update a single
    `data-active` attribute at runtime to drive route highlighting.

Re-run this whenever mctrot_map.svg changes.
"""
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
SVG_PATH = HERE / "mctrot_map.svg"
ELM_OUT = HERE / "src" / "MctrotMapData.elm"
CSS_OUT = HERE / "mctrot_map.css"

NS = "{http://www.w3.org/2000/svg}"


def elm_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    root = ET.parse(SVG_PATH).getroot()

    view_box = root.get("viewBox")

    borough_path_el = root.find(f".//{NS}g[@id='layer-borough']/{NS}path")
    borough_d = borough_path_el.get("d")

    locations = []
    for circle in root.findall(f".//{NS}g[@id='layer-locations']/{NS}circle"):
        mcd_id = int(circle.get("data-mcd-id"))
        cx = float(circle.get("cx"))
        cy = float(circle.get("cy"))
        locations.append((mcd_id, cx, cy))
    locations.sort(key=lambda t: t[0])
    assert len(locations) == 47, f"expected 47 locations, found {len(locations)}"

    edges = []
    for path in root.findall(f".//{NS}g[@id='layer-routes']/{NS}path"):
        edges.append((path.get("class"), path.get("d")))
    assert edges, "no route-edge paths found"

    write_elm(view_box, borough_d, locations, edges)
    write_css([mcd_id for mcd_id, _, _ in locations])

    print(f"wrote {ELM_OUT} ({len(locations)} locations, {len(edges)} route edges)")
    n = len(locations)
    print(f"wrote {CSS_OUT} ({n * (n - 1) // 2} highlight rules)")


def write_elm(view_box, borough_d, locations, edges):
    ids_list = ", ".join(str(mcd_id) for mcd_id, _, _ in locations)
    coords_list = ", ".join(f"( {cx}, {cy} )" for _, cx, cy in locations)
    edges_list = ",\n    ".join(
        f"{{ classes = {elm_string(classes)}, d = {elm_string(d)} }}"
        for classes, d in edges
    )

    elm_source = f"""module MctrotMapData exposing (boroughPath, locationCoords, mapViewBox, mcdIds, routeEdges)

{{-| Generated by examples/generate_map_data.py from examples/mctrot_map.svg.
Do not hand-edit; re-run the script instead.
-}}

import Array exposing (Array)


mapViewBox : String
mapViewBox =
    {elm_string(view_box)}


{{-| The single Manhattan borough silhouette path, verbatim from the source SVG.
-}}
boroughPath : String
boroughPath =
    {elm_string(borough_d)}


{{-| The real `mcd_id` (see examples/mcd_locations.csv) for each stop, in the
same ascending order as Mctrot's `cities` array -- so `Array.get i mcdIds`
gives the id for city index `i`.
-}}
mcdIds : Array Int
mcdIds =
    Array.fromList [ {ids_list} ]


{{-| Real (x, y) coordinates for each stop, same index order as `mcdIds` and
`cities`.
-}}
locationCoords : Array ( Float, Float )
locationCoords =
    Array.fromList [ {coords_list} ]


{{-| Every real-street road segment in the routing layer. Each `classes`
string already includes every `lX-lY` token (X, Y are `mcdIds` values) whose
shortest route crosses that segment -- see mctrot_map.css for the
`[data-active~="lX-lY"] .lX-lY` highlight rules these tokens drive.
-}}
routeEdges : List {{ classes : String, d : String }}
routeEdges =
    [ {edges_list}
    ]
"""
    ELM_OUT.write_text(elm_source)


def write_css(mcd_ids):
    lines = [
        ".borough { fill: #000; stroke: #999; stroke-width: 20; }",
        ".route-edge { fill: none; stroke: #ccc; stroke-width: 55; transition: stroke 150ms ease, stroke-width 150ms ease; }",
        ".location { fill: #FF0000; stroke: #fff; stroke-width: 4; }",
        "",
    ]
    n = len(mcd_ids)
    for i in range(n):
        for j in range(i + 1, n):
            token = f"l{mcd_ids[i]}-l{mcd_ids[j]}"
            lines.append(
                f'[data-active~="{token}"] .{token} {{ stroke: #FFD100; stroke-width: 500; }}'
            )
    CSS_OUT.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
